/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo.index'
import { Route as CatalogoCategoriaSlugRouteRouteImport } from './routes/catalogo.$categoriaSlug.route'
import { Route as CatalogoCategoriaSlugIndexRouteImport } from './routes/catalogo.$categoriaSlug.index'
import { Route as CatalogoTelhasFibrocimentoRouteImport } from './routes/catalogo.telhas.fibrocimento'
import { Route as CatalogoTelhasColonialPvcRouteImport } from './routes/catalogo.telhas.colonial-pvc'
import { Route as CatalogoTelhasCeramicaRouteImport } from './routes/catalogo.telhas.ceramica'
import { Route as CatalogoMadeiramentoEucaliptoRouteImport } from './routes/catalogo.madeiramento.eucalipto'
import { Route as CatalogoMadeiramentoCambaraRouteImport } from './routes/catalogo.madeiramento.cambara'
import { Route as CatalogoCategoriaSlugProdutoSlugRouteImport } from './routes/catalogo.$categoriaSlug.$produtoSlug'

const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoCategoriaSlugRouteRoute =
  CatalogoCategoriaSlugRouteRouteImport.update({
    id: '/catalogo/$categoriaSlug',
    path: '/catalogo/$categoriaSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalogoCategoriaSlugIndexRoute =
  CatalogoCategoriaSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CatalogoCategoriaSlugRouteRoute,
  } as any)
const CatalogoTelhasFibrocimentoRoute =
  CatalogoTelhasFibrocimentoRouteImport.update({
    id: '/catalogo/telhas/fibrocimento',
    path: '/catalogo/telhas/fibrocimento',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalogoTelhasColonialPvcRoute =
  CatalogoTelhasColonialPvcRouteImport.update({
    id: '/catalogo/telhas/colonial-pvc',
    path: '/catalogo/telhas/colonial-pvc',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalogoTelhasCeramicaRoute = CatalogoTelhasCeramicaRouteImport.update({
  id: '/catalogo/telhas/ceramica',
  path: '/catalogo/telhas/ceramica',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoMadeiramentoEucaliptoRoute =
  CatalogoMadeiramentoEucaliptoRouteImport.update({
    id: '/catalogo/madeiramento/eucalipto',
    path: '/catalogo/madeiramento/eucalipto',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalogoMadeiramentoCambaraRoute =
  CatalogoMadeiramentoCambaraRouteImport.update({
    id: '/catalogo/madeiramento/cambara',
    path: '/catalogo/madeiramento/cambara',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalogoCategoriaSlugProdutoSlugRoute =
  CatalogoCategoriaSlugProdutoSlugRouteImport.update({
    id: '/$produtoSlug',
    path: '/$produtoSlug',
    getParentRoute: () => CatalogoCategoriaSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/catalogo/$categoriaSlug': typeof CatalogoCategoriaSlugRouteRouteWithChildren
  '/catalogo/': typeof CatalogoIndexRoute
  '/catalogo/$categoriaSlug/$produtoSlug': typeof CatalogoCategoriaSlugProdutoSlugRoute
  '/catalogo/madeiramento/cambara': typeof CatalogoMadeiramentoCambaraRoute
  '/catalogo/madeiramento/eucalipto': typeof CatalogoMadeiramentoEucaliptoRoute
  '/catalogo/telhas/ceramica': typeof CatalogoTelhasCeramicaRoute
  '/catalogo/telhas/colonial-pvc': typeof CatalogoTelhasColonialPvcRoute
  '/catalogo/telhas/fibrocimento': typeof CatalogoTelhasFibrocimentoRoute
  '/catalogo/$categoriaSlug/': typeof CatalogoCategoriaSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/catalogo': typeof CatalogoIndexRoute
  '/catalogo/$categoriaSlug/$produtoSlug': typeof CatalogoCategoriaSlugProdutoSlugRoute
  '/catalogo/madeiramento/cambara': typeof CatalogoMadeiramentoCambaraRoute
  '/catalogo/madeiramento/eucalipto': typeof CatalogoMadeiramentoEucaliptoRoute
  '/catalogo/telhas/ceramica': typeof CatalogoTelhasCeramicaRoute
  '/catalogo/telhas/colonial-pvc': typeof CatalogoTelhasColonialPvcRoute
  '/catalogo/telhas/fibrocimento': typeof CatalogoTelhasFibrocimentoRoute
  '/catalogo/$categoriaSlug': typeof CatalogoCategoriaSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/catalogo/$categoriaSlug': typeof CatalogoCategoriaSlugRouteRouteWithChildren
  '/catalogo/': typeof CatalogoIndexRoute
  '/catalogo/$categoriaSlug/$produtoSlug': typeof CatalogoCategoriaSlugProdutoSlugRoute
  '/catalogo/madeiramento/cambara': typeof CatalogoMadeiramentoCambaraRoute
  '/catalogo/madeiramento/eucalipto': typeof CatalogoMadeiramentoEucaliptoRoute
  '/catalogo/telhas/ceramica': typeof CatalogoTelhasCeramicaRoute
  '/catalogo/telhas/colonial-pvc': typeof CatalogoTelhasColonialPvcRoute
  '/catalogo/telhas/fibrocimento': typeof CatalogoTelhasFibrocimentoRoute
  '/catalogo/$categoriaSlug/': typeof CatalogoCategoriaSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculadora'
    | '/catalogo/$categoriaSlug'
    | '/catalogo/'
    | '/catalogo/$categoriaSlug/$produtoSlug'
    | '/catalogo/madeiramento/cambara'
    | '/catalogo/madeiramento/eucalipto'
    | '/catalogo/telhas/ceramica'
    | '/catalogo/telhas/colonial-pvc'
    | '/catalogo/telhas/fibrocimento'
    | '/catalogo/$categoriaSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadora'
    | '/catalogo'
    | '/catalogo/$categoriaSlug/$produtoSlug'
    | '/catalogo/madeiramento/cambara'
    | '/catalogo/madeiramento/eucalipto'
    | '/catalogo/telhas/ceramica'
    | '/catalogo/telhas/colonial-pvc'
    | '/catalogo/telhas/fibrocimento'
    | '/catalogo/$categoriaSlug'
  id:
    | '__root__'
    | '/'
    | '/calculadora'
    | '/catalogo/$categoriaSlug'
    | '/catalogo/'
    | '/catalogo/$categoriaSlug/$produtoSlug'
    | '/catalogo/madeiramento/cambara'
    | '/catalogo/madeiramento/eucalipto'
    | '/catalogo/telhas/ceramica'
    | '/catalogo/telhas/colonial-pvc'
    | '/catalogo/telhas/fibrocimento'
    | '/catalogo/$categoriaSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraRoute: typeof CalculadoraRoute
  CatalogoCategoriaSlugRouteRoute: typeof CatalogoCategoriaSlugRouteRouteWithChildren
  CatalogoIndexRoute: typeof CatalogoIndexRoute
  CatalogoMadeiramentoCambaraRoute: typeof CatalogoMadeiramentoCambaraRoute
  CatalogoMadeiramentoEucaliptoRoute: typeof CatalogoMadeiramentoEucaliptoRoute
  CatalogoTelhasCeramicaRoute: typeof CatalogoTelhasCeramicaRoute
  CatalogoTelhasColonialPvcRoute: typeof CatalogoTelhasColonialPvcRoute
  CatalogoTelhasFibrocimentoRoute: typeof CatalogoTelhasFibrocimentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$categoriaSlug': {
      id: '/catalogo/$categoriaSlug'
      path: '/catalogo/$categoriaSlug'
      fullPath: '/catalogo/$categoriaSlug'
      preLoaderRoute: typeof CatalogoCategoriaSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$categoriaSlug/': {
      id: '/catalogo/$categoriaSlug/'
      path: '/'
      fullPath: '/catalogo/$categoriaSlug/'
      preLoaderRoute: typeof CatalogoCategoriaSlugIndexRouteImport
      parentRoute: typeof CatalogoCategoriaSlugRouteRoute
    }
    '/catalogo/telhas/fibrocimento': {
      id: '/catalogo/telhas/fibrocimento'
      path: '/catalogo/telhas/fibrocimento'
      fullPath: '/catalogo/telhas/fibrocimento'
      preLoaderRoute: typeof CatalogoTelhasFibrocimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/telhas/colonial-pvc': {
      id: '/catalogo/telhas/colonial-pvc'
      path: '/catalogo/telhas/colonial-pvc'
      fullPath: '/catalogo/telhas/colonial-pvc'
      preLoaderRoute: typeof CatalogoTelhasColonialPvcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/telhas/ceramica': {
      id: '/catalogo/telhas/ceramica'
      path: '/catalogo/telhas/ceramica'
      fullPath: '/catalogo/telhas/ceramica'
      preLoaderRoute: typeof CatalogoTelhasCeramicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/madeiramento/eucalipto': {
      id: '/catalogo/madeiramento/eucalipto'
      path: '/catalogo/madeiramento/eucalipto'
      fullPath: '/catalogo/madeiramento/eucalipto'
      preLoaderRoute: typeof CatalogoMadeiramentoEucaliptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/madeiramento/cambara': {
      id: '/catalogo/madeiramento/cambara'
      path: '/catalogo/madeiramento/cambara'
      fullPath: '/catalogo/madeiramento/cambara'
      preLoaderRoute: typeof CatalogoMadeiramentoCambaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$categoriaSlug/$produtoSlug': {
      id: '/catalogo/$categoriaSlug/$produtoSlug'
      path: '/$produtoSlug'
      fullPath: '/catalogo/$categoriaSlug/$produtoSlug'
      preLoaderRoute: typeof CatalogoCategoriaSlugProdutoSlugRouteImport
      parentRoute: typeof CatalogoCategoriaSlugRouteRoute
    }
  }
}

interface CatalogoCategoriaSlugRouteRouteChildren {
  CatalogoCategoriaSlugProdutoSlugRoute: typeof CatalogoCategoriaSlugProdutoSlugRoute
  CatalogoCategoriaSlugIndexRoute: typeof CatalogoCategoriaSlugIndexRoute
}

const CatalogoCategoriaSlugRouteRouteChildren: CatalogoCategoriaSlugRouteRouteChildren =
  {
    CatalogoCategoriaSlugProdutoSlugRoute:
      CatalogoCategoriaSlugProdutoSlugRoute,
    CatalogoCategoriaSlugIndexRoute: CatalogoCategoriaSlugIndexRoute,
  }

const CatalogoCategoriaSlugRouteRouteWithChildren =
  CatalogoCategoriaSlugRouteRoute._addFileChildren(
    CatalogoCategoriaSlugRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraRoute: CalculadoraRoute,
  CatalogoCategoriaSlugRouteRoute: CatalogoCategoriaSlugRouteRouteWithChildren,
  CatalogoIndexRoute: CatalogoIndexRoute,
  CatalogoMadeiramentoCambaraRoute: CatalogoMadeiramentoCambaraRoute,
  CatalogoMadeiramentoEucaliptoRoute: CatalogoMadeiramentoEucaliptoRoute,
  CatalogoTelhasCeramicaRoute: CatalogoTelhasCeramicaRoute,
  CatalogoTelhasColonialPvcRoute: CatalogoTelhasColonialPvcRoute,
  CatalogoTelhasFibrocimentoRoute: CatalogoTelhasFibrocimentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
